# Use an official Ubuntu as a parent image
FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive

# Set the working directory
WORKDIR /app

# Install dependencies
# Install Bazelisk and dependencies for arm64
RUN apt-get update && apt-get install -y \
    curl \
    unzip \
    gnupg \
    build-essential \
    python3 \
    python3-pip \
    libgl1 \
    libglib2.0-0 \
    && curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.17.0/bazelisk-linux-arm64" \
    && chmod +x bazelisk-linux-arm64 \
    && mv bazelisk-linux-arm64 /usr/local/bin/bazel

# Create a non-root user and group
RUN groupadd -r appuser && useradd -m -r -g appuser appuser

# Change ownership of the working directory
RUN chown -R appuser:appuser /app

# Switch to the non-root user
USER appuser

# Verify the installation
RUN bazel version

# Set the entry point
ENTRYPOINT ["bazel"]
